apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ${KUBE_DEPLOYMENT_NAME}
spec:
  revisionHistoryLimit: 1
  replicas: 1
  template:
    metadata:
      labels:
        app: ${KUBE_DEPLOYMENT_NAME}
    spec:
      containers:
      - name: $KUBE_DEPLOYMENT_CONTAINER_NAME
        image: gcr.io/${PROJECT_NAME}/${DOCKER_IMAGE_NAME}:$TRAVIS_COMMIT
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
        resources:
          limits:
            cpu: 70m
            memory: 50M
          requests:
            cpu: 70m
            memory: 50M
---
apiVersion: v1
kind: Service
metadata:
  name: ${KUBE_DEPLOYMENT_NAME}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: ${KUBE_DEPLOYMENT_NAME}